spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ghsicilianotfi
    username: root
    password: root
  jpa:  
        show-sql: true
        generate-ddl: true
        hibernate:
            ddl-auto: create
        properties:
            dialect: org.hibernate.dialect.MySQL5Dialect
            hibernate:
                format_sql: true
  thymeleaf:
    cache: false